suman:
    server: <SUSE Manager Server fqdn>
    user: <SUSE Manager account with engough rights te perform needed actions>
    password: <password>

smtp:
   # sendmail: True is a mail should be send for minor and major errors. False if no mail should be send     
   sendmail: True
   receivers:
     - <mail reciepent 1>
     - <mail reciepent 2>
     - <mail reciepent 3>
     - ....
     - <mail reciepent n>

   sender: <sender of the mail>
   server: <smtp server>

dirs:
   log_dir: /var/log/rhn

maintenance:
   exclude_for_patch:
      - lx0001
      - lx0002
   sp_migration:
      sles12-sp1: sles12-sp4
      sles12-sp2: sles12-sp4
      sles12-sp3: sles12-sp4
      sles15-sp0: sles15-sp1
   exception_sp:
      sles12-sp4:
      - lx0003
      - lx0004

channel_cloner:
   sles-11-sp4-x86_64:
      base_channel: sles11-sp4-pool-x86_64
      channels:
        - sles11-sp4-updates-x86_64,RELEASE-sles11-sp4-updates-x86_64
        - sle11-sdk-sp4-pool-x86_64,RELEASE-sle11-sdk-sp4-pool-x86_64
        - sle11-sdk-sp4-updates-x86_64,RELEASE-sle11-sdk-sp4-updates-x86_64
        - sles11-sp4-suse-manager-tools-x86_64,RELEASE-sle11-sdk-sp4-updates-x86_64

   sles-12-sp2-x86_64:
      base_channel: sles12-sp2-pool-x86_64
      channels:
        - sle-sdk12-sp2-pool-x86_64,RELEASE-sle-sdk12-sp2-pool-x86_64
        - sle-sdk12-sp2-updates-x86_64,RELEASE-sle-sdk12-sp2-updates-x86_64
        - sles12-sp2-updates-x86_64,RELEASE-sles12-sp2-updates-x86_64
        - sle-manager-tools12-pool-x86_64-sp2,RELEASE-sle-manager-tools12-pool-x86_64-sp2
        - sle-manager-tools12-updates-x86_64-sp2,RELEASE-sle-manager-tools12-updates-x86_64-sp2

   sles-12-sp3-x86_64:
      base_channel: sles12-sp3-pool-x86_64
      channels:
        - sles12-sp3-updates-x86_64,RELEASE-sles12-sp3-updates-x86_64
        - sle-manager-tools12-pool-x86_64-sp3,RELEASE-sle-manager-tools12-pool-x86_64-sp3
        - sle-manager-tools12-updates-x86_64-sp3,RELEASE-sle-manager-tools12-updates-x86_64-sp3

   sles-12-sp4-x86_64:
      base_channel: sles12-sp4-pool-x86_64
      channels:
        - sle-sdk12-sp4-pool-x86_64,RELEASE-sle-sdk12-sp4-pool-x86_64
        - sle-sdk12-sp4-updates-x86_64,RELEASE-sle-sdk12-sp4-updates-x86_64
        - sles12-sp4-updates-x86_64,RELEASE-sles12-sp4-updates-x86_64
        - sle-manager-tools12-pool-x86_64-sp4,RELEASE-sle-manager-tools12-pool-x86_64-sp4
        - sle-manager-tools12-updates-x86_64-sp4,RELEASE-sle-manager-tools12-updates-x86_64-sp4
        - sle-module-adv-systems-management12-pool-x86_64-sp4,RELEASE-sle-module-adv-systems-management12-pool-x86_64-sp4
        - sle-module-adv-systems-management12-updates-x86_64-sp4,RELEASE-sle-module-adv-systems-management12-updates-x86_64-sp4

